# This file was generated by GoReleaser. DO NOT EDIT.
cask "mek" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "6d9d62751d238f7af116fee94bfa47f8dd7089bbed69211f1e762b2d2e0dbdc3"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f5043498da4d94ee99843cf154aba9639c2988b8b81e119670cde6cbd1124a6"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "96642301579c297f45bd0d5d6495604bd9ac94831c2dba2f456fb97c29e40987"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7fd07603b6593d481ecaa21871e577283cb8c2acad773ab799877c63ca44b80"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_amd64.tar.gz"
    end
  end

  name "mek"
  desc "Log in, switch and run commands across AWS and GCP"
  homepage "https://github.com/prateep-r/mek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mek"]
    end
  end

  # No zap stanza required
end
