# This file was generated by GoReleaser. DO NOT EDIT.
cask "mek" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "ab810b4603c05ae3ad988634e8a6ac2a693154dc0716d51168f946cc68fdc61b"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c69250535449ebfca2331a65b44f7e3864525290ee2e5e98c17c4e54322fb094"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59218743f1c2f25b062cc814c5fa4d05e57bfa201b73598350d22d3095e82f16"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f31910933ecdbe081878a5bfdf1cd15de0a48d73a011252460785c0d98681c0d"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_amd64.tar.gz"
    end
  end

  name "mek"
  desc "Log in, switch and run commands across AWS, GCP, Azure and Huawei Cloud"
  homepage "https://github.com/prateep-r/mek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mek"]
    end
  end

  # No zap stanza required
end
