# This file was generated by GoReleaser. DO NOT EDIT.
cask "mek" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "e323f821b3405f9d3a2ceb796d541206ca6fc8e0cf0b9923971f716380eb4473"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b47062105f2ce6e706175bc8ac64cfe8e7735b5826625f1c8a1e99296564614e"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aefaf5f7c7a95caf79db55d5216e359b977dc1fc60cec3e92335db21c8de176c"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b90890791b179b647432155569e03d0c692eca0e2ad75c5f8b1d7172e5b20d3"
      url "https://github.com/prateep-r/mek/releases/download/v#{version}/mek_linux_amd64.tar.gz"
    end
  end

  name "mek"
  desc "Log in, switch and run commands across AWS, GCP, Azure and Huawei Cloud"
  homepage "https://github.com/prateep-r/mek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mek"]
    end
  end

  # No zap stanza required
end
